### ISSUE TITLE
Mixing up train vs test data?

### ISSUE THREAD

**Issue by yhanafy** [mnielLab/NetTCR-2.0#3]
I noticed that on line 65 that it appears that you may have mixed up the testing and training data causing you to train on the testing data. Is this correct?

Code line:
https://github.com/mnielLab/NetTCR-2.0/blob/main/nettcr.py#L65

**Comment by montallen** [comment]
Hi @yhanafy, thanks for the comment. 
That was a mistake in the code. Now it should be correct.
